// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFy8Q8SWWiGQ4lh1yON0dxn0jVy5Lq8nk',
    appId: '1:924684180668:web:4aea87a38556d3e0f144b9',
    messagingSenderId: '924684180668',
    projectId: 'refab-app',
    authDomain: 'refab-app.firebaseapp.com',
    storageBucket: 'refab-app.firebasestorage.app',
    measurementId: 'G-6C6E0JD1EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlePAsvJ0L3IwAMh7dalBGKFa7czfqxDQ',
    appId: '1:924684180668:android:17fa4d73fe37b981f144b9',
    messagingSenderId: '924684180668',
    projectId: 'refab-app',
    storageBucket: 'refab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_VzoofmMvUjN6kbXkf26F3C6fNVI9so',
    appId: '1:924684180668:ios:8295a911d356674bf144b9',
    messagingSenderId: '924684180668',
    projectId: 'refab-app',
    storageBucket: 'refab-app.firebasestorage.app',
    iosBundleId: 'com.refab.refabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz_VzoofmMvUjN6kbXkf26F3C6fNVI9so',
    appId: '1:924684180668:ios:8295a911d356674bf144b9',
    messagingSenderId: '924684180668',
    projectId: 'refab-app',
    storageBucket: 'refab-app.firebasestorage.app',
    iosBundleId: 'com.refab.refabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFy8Q8SWWiGQ4lh1yON0dxn0jVy5Lq8nk',
    appId: '1:924684180668:web:62c97326ad089c59f144b9',
    messagingSenderId: '924684180668',
    projectId: 'refab-app',
    authDomain: 'refab-app.firebaseapp.com',
    storageBucket: 'refab-app.firebasestorage.app',
    measurementId: 'G-T6KJFNY1JX',
  );

}